// Math Vocabulary Library - Kid-friendly definitions with examples

export interface VocabularyTerm {
  id: string;
  termJa: string;
  termEn: string;
  emoji: string;
  simpleDefinitionJa: string;
  simpleDefinitionEn: string;
  detailedDefinitionJa: string;
  detailedDefinitionEn: string;
  exampleJa: string;
  exampleEn: string;
  exampleVisual?: string;
  relatedTerms: string[];
  category: 'arithmetic' | 'fractions' | 'geometry' | 'measurement' | 'ratios' | 'general';
}

export const VOCABULARY_TERMS: VocabularyTerm[] = [
  // Arithmetic Terms
  {
    id: 'divisor',
    termJa: 'わる数',
    termEn: 'Divisor',
    emoji: '➗',
    simpleDefinitionJa: 'わり算で、わる方の数',
    simpleDefinitionEn: 'The number we divide BY',
    detailedDefinitionJa: 'わり算の式の中で、何個にわけるか、または何人でわけるかをあらわす数です',
    detailedDefinitionEn: 'In division, this tells us how many groups we\'re making or how many items are in each group',
    exampleJa: '12 ÷ 3 = 4 のとき、3がわる数',
    exampleEn: 'In 12 ÷ 3 = 4: 3 is the divisor',
    exampleVisual: '🔴🔴🔴 🔴🔴🔴 🔴🔴🔴 🔴🔴🔴\n12を3つのグループにわける',
    relatedTerms: ['dividend', 'quotient', 'remainder'],
    category: 'arithmetic',
  },
  {
    id: 'dividend',
    termJa: 'わられる数',
    termEn: 'Dividend',
    emoji: '📦',
    simpleDefinitionJa: 'わり算で、わられる方の数',
    simpleDefinitionEn: 'The number being divided',
    detailedDefinitionJa: 'わり算の式の中で、わられる対象の総数です',
    detailedDefinitionEn: 'The total amount or number that we want to split into equal groups',
    exampleJa: '12 ÷ 3 = 4 のとき、12がわられる数',
    exampleEn: 'In 12 ÷ 3 = 4: 12 is the dividend',
    exampleVisual: '🍎🍎🍎🍎🍎🍎🍎🍎🍎🍎🍎🍎\n12個のりんご',
    relatedTerms: ['divisor', 'quotient', 'remainder'],
    category: 'arithmetic',
  },
  {
    id: 'quotient',
    termJa: '答え（わり算）',
    termEn: 'Quotient',
    emoji: '✨',
    simpleDefinitionJa: 'わり算の答え',
    simpleDefinitionEn: 'The answer to a division problem',
    detailedDefinitionJa: 'わり算の結果、1つあたり何個になるか、またはいくつのグループになるかをあらわす数です',
    detailedDefinitionEn: 'The result of division - how many are in each group, or how many groups we made',
    exampleJa: '12 ÷ 3 = 4 のとき、4が答え',
    exampleEn: 'In 12 ÷ 3 = 4: 4 is the quotient',
    exampleVisual: '3 × 4 = 12 ともいえるよ',
    relatedTerms: ['divisor', 'dividend', 'remainder'],
    category: 'arithmetic',
  },
  {
    id: 'remainder',
    termJa: 'あまり',
    termEn: 'Remainder',
    emoji: '🎁',
    simpleDefinitionJa: 'わり切れなかった残り',
    simpleDefinitionEn: 'What\'s left over after dividing',
    detailedDefinitionJa: 'わり算で、等しくわりきれなかったあまりの数です。あまりは、わる数より小さくなります',
    detailedDefinitionEn: 'The amount left over when a number can\'t be divided equally. The remainder is always smaller than the divisor',
    exampleJa: '13 ÷ 3 = 4 あまり 1',
    exampleEn: '13 ÷ 3 = 4 remainder 1',
    exampleVisual: '🍎🍎🍎 🍎🍎🍎 🍎🍎🍎 🍎🍎🍎 🍎\n4つずつ3グループと、あまり1',
    relatedTerms: ['divisor', 'dividend', 'quotient'],
    category: 'arithmetic',
  },
  {
    id: 'multiple',
    termJa: '倍数（ばいすう）',
    termEn: 'Multiple',
    emoji: '📊',
    simpleDefinitionJa: 'かけ算の答えの表にでてくる数',
    simpleDefinitionEn: 'Numbers in the times tables',
    detailedDefinitionJa: 'ある数を1倍、2倍、3倍...としたときの答えです。かけ算の表（九九）にでてくる数です',
    detailedDefinitionEn: 'The result of multiplying a number by 1, 2, 3, etc. All the answers you see in multiplication tables',
    exampleJa: '3の倍数: 3, 6, 9, 12, 15, 18...',
    exampleEn: 'Multiples of 3: 3, 6, 9, 12, 15, 18...',
    exampleVisual: '3×1=3, 3×2=6, 3×3=9...',
    relatedTerms: ['factor', 'times', 'product'],
    category: 'arithmetic',
  },
  {
    id: 'factor',
    termJa: '約数（やくすう）',
    termEn: 'Factor',
    emoji: '🧩',
    simpleDefinitionJa: 'ある数をわり切れる数',
    simpleDefinitionEn: 'Numbers that divide evenly into another number',
    detailedDefinitionJa: 'ある数をわったときに、あまりがでないでわり切れる数です。かけ算でその数を作ることができる数の組み合わせです',
    detailedDefinitionEn: 'Numbers that can multiply together to make another number. A number that divides evenly with no remainder',
    exampleJa: '12の約数: 1, 2, 3, 4, 6, 12\n(1×12, 2×6, 3×4)',
    exampleEn: 'Factors of 12: 1, 2, 3, 4, 6, 12\n(1×12, 2×6, 3×4)',
    exampleVisual: '12 = 3 × 4\n3と4は12の約数',
    relatedTerms: ['multiple', 'divisor', 'product'],
    category: 'arithmetic',
  },
  {
    id: 'product',
    termJa: '答え（かけ算）',
    termEn: 'Product',
    emoji: '✖️',
    simpleDefinitionJa: 'かけ算の答え',
    simpleDefinitionEn: 'The answer to a multiplication problem',
    detailedDefinitionJa: 'かけ算の結果、合計がいくつになったかをあらわす数です',
    detailedDefinitionEn: 'The result when two or more numbers are multiplied together',
    exampleJa: '3 × 4 = 12 のとき、12が答え',
    exampleEn: 'In 3 × 4 = 12: 12 is the product',
    exampleVisual: '🍎🍎🍎\n🍎🍎🍎\n🍎🍎🍎\n🍎🍎🍎\n3×4=12個',
    relatedTerms: ['factor', 'multiple', 'times'],
    category: 'arithmetic',
  },
  {
    id: 'sum',
    termJa: '答え（たし算）',
    termEn: 'Sum',
    emoji: '➕',
    simpleDefinitionJa: 'たし算の答え',
    simpleDefinitionEn: 'The answer to an addition problem',
    detailedDefinitionJa: 'たし算の結果、ぜんぶでいくつになったかをあらわす数です',
    detailedDefinitionEn: 'The result when two or more numbers are added together',
    exampleJa: '5 + 3 = 8 のとき、8が答え',
    exampleEn: 'In 5 + 3 = 8: 8 is the sum',
    exampleVisual: '⚫⚫⚫⚫⚫ + ⚫⚫⚫ = ⚫⚫⚫⚫⚫⚫⚫⚫',
    relatedTerms: ['addend', 'difference'],
    category: 'arithmetic',
  },
  {
    id: 'difference',
    termJa: '答え（ひき算）',
    termEn: 'Difference',
    emoji: '➖',
    simpleDefinitionJa: 'ひき算の答え',
    simpleDefinitionEn: 'The answer to a subtraction problem',
    detailedDefinitionJa: 'ひき算の結果、2つの数の差（ちがい）がいくつかをあらわす数です',
    detailedDefinitionEn: 'The result when one number is subtracted from another - it tells us how different two numbers are',
    exampleJa: '10 - 3 = 7 のとき、7が答え\n「差は7」',
    exampleEn: 'In 10 - 3 = 7: 7 is the difference',
    exampleVisual: '⚫⚫⚫⚫⚫⚫⚫⚫⚫⚫\nー ⚫⚫⚫\n= ⚫⚫⚫⚫⚫⚫⚫',
    relatedTerms: ['subtrahend', 'minuend', 'sum'],
    category: 'arithmetic',
  },

  // Fraction Terms
  {
    id: 'numerator',
    termJa: '分子（ぶんし）',
    termEn: 'Numerator',
    emoji: '⬆️',
    simpleDefinitionJa: '分数の上の数',
    simpleDefinitionEn: 'The top number in a fraction',
    detailedDefinitionJa: '分数の上に書かれる数で、とった個数や部分の大きさをあらわします',
    detailedDefinitionEn: 'The top number of a fraction that tells us how many parts we have or are considering',
    exampleJa: '3/5 のとき、3が分子\n「5等分のうち3つ」',
    exampleEn: 'In 3/5: 3 is the numerator\n"3 out of 5 equal parts"',
    exampleVisual: '🍕🍕🍕⬜⬜\n3/5枚のピザ',
    relatedTerms: ['denominator', 'fraction'],
    category: 'fractions',
  },
  {
    id: 'denominator',
    termJa: '分母（ぶんぼ）',
    termEn: 'Denominator',
    emoji: '⬇️',
    simpleDefinitionJa: '分数の下の数',
    simpleDefinitionEn: 'The bottom number in a fraction',
    detailedDefinitionJa: '分数の下に書かれる数で、全部でいくつにわけたかをあらわします',
    detailedDefinitionEn: 'The bottom number of a fraction that tells us how many equal parts the whole is divided into',
    exampleJa: '3/5 のとき、5が分母\n「5等分したうち」',
    exampleEn: 'In 3/5: 5 is the denominator\n"divided into 5 equal parts"',
    exampleVisual: '🍕🍕🍕🍕🍕\n5等分されたピザ',
    relatedTerms: ['numerator', 'fraction'],
    category: 'fractions',
  },
  {
    id: 'fraction',
    termJa: '分数（ぶんすう）',
    termEn: 'Fraction',
    emoji: '🍕',
    simpleDefinitionJa: 'ものをわけるときの数',
    simpleDefinitionEn: 'Numbers we use when sharing things',
    detailedDefinitionJa: '1より小さい数や、1と分数を合わせた数をあらわす方法です。ものを等分するときにつかいます',
    detailedDefinitionEn: 'A way to show parts of a whole number. We use fractions when we divide things into equal parts',
    exampleJa: '1/2（2等分の1）、3/4（4等分の3）',
    exampleEn: '1/2 (one of two equal parts), 3/4 (three of four equal parts)',
    exampleVisual: '🍕 → 🍕|🍕 → 1/2',
    relatedTerms: ['numerator', 'denominator'],
    category: 'fractions',
  },
  {
    id: 'mixed-number',
    termJa: '帯分数（たいぶんすう）',
    termEn: 'Mixed Number',
    emoji: '🧁',
    simpleDefinitionJa: '整数と分数を合わせた数',
    simpleDefinitionEn: 'A whole number and a fraction together',
    detailedDefinitionJa: '1より大きい数で、整数の部分と分数の部分を合わせて書いた数です',
    detailedDefinitionEn: 'A number that combines a whole number with a fraction, representing something larger than 1',
    exampleJa: '1 1/2（いちと2ぶんの1）',
    exampleEn: '1 1/2 (one and one half)',
    exampleVisual: '🧁🧁 + 🧁/2 = 1 1/2',
    relatedTerms: ['fraction', 'improper-fraction'],
    category: 'fractions',
  },
  {
    id: 'improper-fraction',
    termJa: '仮分数（かぶんすう）',
    termEn: 'Improper Fraction',
    emoji: '📈',
    simpleDefinitionJa: '分子が分母より大きい分数',
    simpleDefinitionEn: 'A fraction where the top is bigger than the bottom',
    detailedDefinitionJa: '分子（上）が分母（下）より大きくて、1より大きい値をもつ分数です',
    detailedDefinitionEn: 'A fraction where the numerator is larger than the denominator, making it greater than 1',
    exampleJa: '5/4（5÷4=1.25）、7/3',
    exampleEn: '5/4 (5÷4=1.25), 7/3',
    exampleVisual: '🍕🍕🍕🍕🍕 = 1と1/4',
    relatedTerms: ['fraction', 'mixed-number'],
    category: 'fractions',
  },

  // Geometry Terms
  {
    id: 'parallel',
    termJa: '平行（へいこう）',
    termEn: 'Parallel',
    emoji: '🛤️',
    simpleDefinitionJa: '交わらないまま続く線',
    simpleDefinitionEn: 'Lines that never meet',
    detailedDefinitionJa: '同じ方向を向いていて、どこまで延ばしても交わらない2本の線や辺のことです',
    detailedDefinitionEn: 'Lines or sides that go in the same direction and stay the same distance apart forever without crossing',
    exampleJa: '電車のレール、ノートの横線',
    exampleEn: 'Train tracks, lines on notebook paper',
    exampleVisual: '═══  ═══\n永遠に交わらない',
    relatedTerms: ['perpendicular', 'line', 'intersecting'],
    category: 'geometry',
  },
  {
    id: 'perpendicular',
    termJa: '垂直（すいちょく）',
    termEn: 'Perpendicular',
    emoji: '📐',
    simpleDefinitionJa: '90°で交わる線',
    simpleDefinitionEn: 'Lines that meet at 90° angles',
    detailedDefinitionJa: '2本の線や辺が交わる角度が90°（直角）になることです。+の形や、□の角にみられます',
    detailedDefinitionEn: 'When two lines or sides meet at a 90° angle (right angle). Looks like a plus sign + or corners of a square',
    exampleJa: '直角をつくる2本の線',
    exampleEn: 'Two lines that make a right angle',
    exampleVisual: '┐\n│\n└──────\n90°の角',
    relatedTerms: ['parallel', 'right-angle', 'intersecting'],
    category: 'geometry',
  },
  {
    id: 'right-angle',
    termJa: '直角（ちょっかく）',
    termEn: 'Right Angle',
    emoji: '📏',
    simpleDefinitionJa: '90°の角',
    simpleDefinitionEn: 'A 90 degree angle',
    detailedDefinitionJa: '角度がちょうど90°の角です。□の記号であらわします。定規の角のような形です',
    detailedDefinitionEn: 'An angle that measures exactly 90 degrees. Marked with a small square symbol □',
    exampleJa: '定規の角、本の角',
    exampleEn: 'Corner of a ruler, corner of a book',
    exampleVisual: '┐\n│  □\n│\n└────',
    relatedTerms: ['perpendicular', 'acute-angle', 'obtuse-angle'],
    category: 'geometry',
  },
  {
    id: 'acute-angle',
    termJa: '鋭角（えいかく）',
    termEn: 'Acute Angle',
    emoji: '🔽',
    simpleDefinitionJa: '90°より小さい角',
    simpleDefinitionEn: 'An angle smaller than 90°',
    detailedDefinitionJa: '90°より小さくて、とがった形の角です。30°や45°、60°などがあります',
    detailedDefinitionEn: 'An angle that measures less than 90 degrees. Looks sharp or pointy',
    exampleJa: '30°、45°、60°など',
    exampleEn: '30°, 45°, 60° angles',
    exampleVisual: '📐（細い開き）\n< 90°',
    relatedTerms: ['right-angle', 'obtuse-angle', 'angle'],
    category: 'geometry',
  },
  {
    id: 'obtuse-angle',
    termJa: '鈍角（どんかく）',
    termEn: 'Obtuse Angle',
    emoji: '🔼',
    simpleDefinitionJa: '90°より大きい角',
    simpleDefinitionEn: 'An angle larger than 90°',
    detailedDefinitionJa: '90°より大きくて、180°より小さい角です。ひらいた形の角です',
    detailedDefinitionEn: 'An angle that measures more than 90 degrees but less than 180 degrees. Looks wide or open',
    exampleJa: '120°、135°など',
    exampleEn: '120°, 135° angles',
    exampleVisual: '📐（ひらいた開き）\n> 90°',
    relatedTerms: ['right-angle', 'acute-angle', 'angle'],
    category: 'geometry',
  },
  {
    id: 'diagonal',
    termJa: '対角線（たいかくせん）',
    termEn: 'Diagonal',
    emoji: '✖️',
    simpleDefinitionJa: '角と角を結ぶ線',
    simpleDefinitionEn: 'A line connecting opposite corners',
    detailedDefinitionJa: '四角形や多角形で、向かい合う頂点（角）を結ぶ線のことです',
    detailedDefinitionEn: 'A straight line inside a shape that connects two opposite corners (vertices)',
    exampleJa: '□ の中の × の線',
    exampleEn: 'The X line inside a square',
    exampleVisual: '◢───◣\n│ ╲╱ │\n│ ╱╲ │\n◥───◤',
    relatedTerms: ['vertex', 'quadrilateral', 'polygon'],
    category: 'geometry',
  },
  {
    id: 'vertex',
    termJa: '頂点（ちょうてん）',
    termEn: 'Vertex',
    emoji: '📍',
    simpleDefinitionJa: '形の角の部分',
    simpleDefinitionEn: 'A corner point of a shape',
    detailedDefinitionJa: '2本以上の辺や線が交わる点のことです。形の角のところにあります',
    detailedDefinitionEn: 'A point where two or more lines, sides, or edges meet to form a corner',
    exampleJa: '△の3つの角、□の4つの角',
    exampleEn: 'The 3 corners of a triangle, 4 corners of a square',
    exampleVisual: '△\n●  ●\n ●\n3つの頂点',
    relatedTerms: ['angle', 'side', 'edge'],
    category: 'geometry',
  },

  // Measurement Terms
  {
    id: 'perimeter',
    termJa: '周囲の長さ（まわり）',
    termEn: 'Perimeter',
    emoji: '🏃',
    simpleDefinitionJa: '形の周りの長さ',
    simpleDefinitionEn: 'The distance around a shape',
    detailedDefinitionJa: '形の外側の辺をすべて足した長さです。形の周りを歩いた距離に相当します',
    detailedDefinitionEn: 'The total length of all the sides of a shape. The distance you would walk if you walked around the edge',
    exampleJa: '長方形の周り = たて+よこ+たて+よこ',
    exampleEn: 'Rectangle perimeter = length + width + length + width',
    exampleVisual: '┌────┐\n│    │ = 2×(縦+横)\n└────┘',
    relatedTerms: ['area', 'length', 'width'],
    category: 'measurement',
  },
  {
    id: 'area',
    termJa: '面積（めんせき）',
    termEn: 'Area',
    emoji: '⬜',
    simpleDefinitionJa: '形の中の広さ',
    simpleDefinitionEn: 'The space inside a shape',
    detailedDefinitionJa: '形の内部の大きさをあらわす量です。1cm²のマスがいくつ入るかで数えます',
    detailedDefinitionEn: 'The amount of space inside a shape. We count how many unit squares (like 1cm²) fit inside',
    exampleJa: '長方形の面積 = たて × よこ',
    exampleEn: 'Rectangle area = length × width',
    exampleVisual: '┌────┐\n│■■■■│ = 縦×横\n│■■■■│\n└────┘',
    relatedTerms: ['perimeter', 'square-unit', 'base', 'height'],
    category: 'measurement',
  },
  {
    id: 'volume',
    termJa: '体積（たいせき）',
    termEn: 'Volume',
    emoji: '📦',
    simpleDefinitionJa: 'ものの大きさ（3次元）',
    simpleDefinitionEn: 'The space a 3D object takes up',
    detailedDefinitionJa: '立体の中に入る大きさです。1cm³の立方体がいくつ入るかで数えます',
    detailedDefinitionEn: 'The amount of space inside a 3D object. We count how many unit cubes (like 1cm³) fit inside',
    exampleJa: '立方体の体積 = 一辺 × 一辺 × 一辺',
    exampleEn: 'Cube volume = side × side × side',
    exampleVisual: '📦📦\n📦📦 = 2×2×2=8',
    relatedTerms: ['capacity', 'cubic-unit', 'area'],
    category: 'measurement',
  },
  {
    id: 'capacity',
    termJa: '容量（ようりょう）',
    termEn: 'Capacity',
    emoji: '🥛',
    simpleDefinitionJa: '入れ物に入る量',
    simpleDefinitionEn: 'How much a container can hold',
    detailedDefinitionJa: 'コップや瓶などの入れ物に、液体やものがどれだけ入るかをあらわす量です',
    detailedDefinitionEn: 'The amount of liquid or material that a container can hold when full',
    exampleJa: 'ペットボトルの容量500ml',
    exampleEn: 'A water bottle with capacity of 500ml',
    exampleVisual: '🍶\n～～～ = 500ml',
    relatedTerms: ['volume', 'liter', 'milliliter'],
    category: 'measurement',
  },

  // Ratio Terms
  {
    id: 'ratio',
    termJa: '比（ひ）',
    termEn: 'Ratio',
    emoji: '⚖️',
    simpleDefinitionJa: '2つの数の関係',
    simpleDefinitionEn: 'The relationship between two numbers',
    detailedDefinitionJa: '2つの量や数の関係をあらわす方法です。A:Bや分数で表します',
    detailedDefinitionEn: 'A way to show how two numbers or quantities compare to each other, written as A:B or a fraction',
    exampleJa: 'りんごとみかんの比 3:2',
    exampleEn: 'Ratio of apples to oranges is 3:2',
    exampleVisual: '🍎🍎🍎 : 🍊🍊',
    relatedTerms: ['proportion', 'times', 'base'],
    category: 'ratios',
  },
  {
    id: 'base',
    termJa: 'もとにする数',
    termEn: 'Base',
    emoji: '🎯',
    simpleDefinitionJa: '比べるときの基準の数',
    simpleDefinitionEn: 'The reference number we compare to',
    detailedDefinitionJa: '「倍」や「比」を考えるときの基準になる数です。いつもの数、または標準の数です',
    detailedDefinitionEn: 'The original or reference number that we use for comparison when talking about "times" or ratios',
    exampleJa: 'AがBの3倍 → Bがもとにする数',
    exampleEn: 'A is 3 times B → B is the base',
    exampleVisual: '📏←基準\nB × 3 = A',
    relatedTerms: ['ratio', 'times', 'compared'],
    category: 'ratios',
  },
  {
    id: 'times',
    termJa: '倍（ばい）',
    termEn: 'Times',
    emoji: '✖️',
    simpleDefinitionJa: 'もとにする数が何個分か',
    simpleDefinitionEn: 'How many groups of the base number',
    detailedDefinitionJa: 'もとにする数をいくつ分集めたかをあらわす数です。2倍、3倍などと言います',
    detailedDefinitionEn: 'How many times larger one number is compared to another. 2 times, 3 times, etc.',
    exampleJa: '6は3の2倍（6÷3=2）',
    exampleEn: '6 is 2 times 3 (6÷3=2)',
    exampleVisual: '⚫⚫⚫ × 2 = ⚫⚫⚫⚫⚫⚫',
    relatedTerms: ['base', 'ratio', 'multiple'],
    category: 'ratios',
  },
  {
    id: 'proportion',
    termJa: '比例（ひれい）',
    termEn: 'Proportion',
    emoji: '📈',
    simpleDefinitionJa: '一方が増えると他方も増える関係',
    simpleDefinitionEn: 'When one amount increases, so does the other',
    detailedDefinitionJa: '2つの量が、一方が2倍、3倍...になると、他方も2倍、3倍...になる関係です',
    detailedDefinitionEn: 'A relationship where if one quantity doubles or triples, the other quantity also doubles or triples',
    exampleJa: 'りんご2個で100円、4個で200円',
    exampleEn: '2 apples cost $1, 4 apples cost $2',
    exampleVisual: '↑ 値段\n│  /\n│ /\n│/\n└──→ 個数',
    relatedTerms: ['ratio', 'linear', 'corresponding'],
    category: 'ratios',
  },

  // General Math Terms
  {
    id: 'equation',
    termJa: '式（しき）',
    termEn: 'Equation',
    emoji: '📝',
    simpleDefinitionJa: '計算の式',
    simpleDefinitionEn: 'A math sentence with numbers and symbols',
    detailedDefinitionJa: '数や記号（+, -, ×, ÷, =）を使って計算の内容をあらわしたものです',
    detailedDefinitionEn: 'A mathematical statement that uses numbers and symbols to show a calculation or relationship',
    exampleJa: '3 + 5 = 8、2 × 4 = 8',
    exampleEn: '3 + 5 = 8, 2 × 4 = 8',
    exampleVisual: 'a + b = c\n2 + 3 = 5',
    relatedTerms: ['expression', 'formula', 'equal'],
    category: 'general',
  },
  {
    id: 'estimate',
    termJa: '概数（がいすう）',
    termEn: 'Estimate',
    emoji: '🔮',
    simpleDefinitionJa: 'おおよその数',
    simpleDefinitionEn: 'A rough or approximate number',
    detailedDefinitionJa: 'ぴったりではなく、だいたいの数のことです。計算を簡単にするために使います',
    detailedDefinitionEn: 'A number that is close to the exact amount but easier to work with. Used for quick calculations',
    exampleJa: '198 ≈ 200（200とおおよそ同じ）',
    exampleEn: '198 ≈ 200 (about the same as 200)',
    exampleVisual: '198 → 【約200】',
    relatedTerms: ['approximate', 'rounding'],
    category: 'general',
  },
  {
    id: 'unit',
    termJa: '単位（たんい）',
    termEn: 'Unit',
    emoji: '📏',
    simpleDefinitionJa: 'ものを数える基準',
    simpleDefinitionEn: 'A standard for measuring',
    detailedDefinitionJa: '長さや重さ、時間などを測るときの基準となるものです。cm、kg、分などがあります',
    detailedDefinitionEn: 'A standard amount or quantity used for measurement, like cm for length, kg for weight, or minutes for time',
    exampleJa: '長さ：cm、m、km\n重さ：g、kg',
    exampleEn: 'Length: cm, m, km\nWeight: g, kg',
    exampleVisual: '📏 = cm\n⚖️ = g',
    relatedTerms: ['measure', 'scale'],
    category: 'general',
  },
  {
    id: 'decimal',
    termJa: '小数（しょうすう）',
    termEn: 'Decimal',
    emoji: '•',
    simpleDefinitionJa: '点（.）を使った数',
    simpleDefinitionEn: 'Numbers using a decimal point',
    detailedDefinitionJa: '1より小さい数を小数点（.）を使ってあらわしたものです。0.5、3.14など',
    detailedDefinitionEn: 'A way to write numbers that are smaller than 1 using a decimal point, like 0.5 or 3.14',
    exampleJa: '0.5（2分の1）、0.25（4分の1）',
    exampleEn: '0.5 (one half), 0.25 (one quarter)',
    exampleVisual: '1 ÷ 2 = 0.5',
    relatedTerms: ['decimal-point', 'fraction'],
    category: 'general',
  },
  {
    id: 'decimal-point',
    termJa: '小数点（しょうすうてん）',
    termEn: 'Decimal Point',
    emoji: '🔵',
    simpleDefinitionJa: '小数の中の点（.）',
    simpleDefinitionEn: 'The dot in a decimal number',
    detailedDefinitionJa: '整数部分と小数部分を分ける点です。左が1の位、右が10分の1の位になります',
    detailedDefinitionEn: 'The dot that separates the whole number part from the fractional part. Left is ones, right is tenths',
    exampleJa: '3.14 の「.」が小数点',
    exampleEn: 'The "." in 3.14 is the decimal point',
    exampleVisual: '3 . 14\n↑ 小数点',
    relatedTerms: ['decimal', 'place-value'],
    category: 'general',
  },
];

// Helper function to get term by ID
export const getTermById = (id: string): VocabularyTerm | undefined => {
  return VOCABULARY_TERMS.find(term => term.id === id);
};

// Helper function to get terms by category
export const getTermsByCategory = (category: VocabularyTerm['category']): VocabularyTerm[] => {
  return VOCABULARY_TERMS.filter(term => term.category === category);
};

// Helper function to search terms
export const searchTerms = (query: string): VocabularyTerm[] => {
  const lowerQuery = query.toLowerCase();
  return VOCABULARY_TERMS.filter(term =>
    term.termJa.includes(query) ||
    term.termEn.toLowerCase().includes(lowerQuery) ||
    term.simpleDefinitionJa.includes(query) ||
    term.simpleDefinitionEn.toLowerCase().includes(lowerQuery)
  );
};

// Category labels for UI
export const CATEGORY_LABELS: Record<VocabularyTerm['category'], { ja: string; en: string; emoji: string }> = {
  arithmetic: { ja: '計算', en: 'Arithmetic', emoji: '🧮' },
  fractions: { ja: '分数', en: 'Fractions', emoji: '🍕' },
  geometry: { ja: '図形', en: 'Geometry', emoji: '📐' },
  measurement: { ja: '測定', en: 'Measurement', emoji: '📏' },
  ratios: { ja: '比・倍', en: 'Ratios', emoji: '⚖️' },
  general: { ja: '一般', en: 'General', emoji: '📚' },
};

// Terms that commonly appear in questions and should be clickable
export const COMMON_MATH_TERMS = [
  'divisor', 'dividend', 'multiple', 'factor',
  'numerator', 'denominator', 'parallel', 'perpendicular',
  'perimeter', 'area', 'ratio', 'base', 'times',
  'decimal', 'fraction', 'diagonal', 'vertex'
];
